var questions = [

[["Ce reprezintă HTML?"],
[["a. Hydro Tesla Markdown List"],
["b. HyperText Markup Language"],
["c. Hipster Technology Making Lasagne"],
["d. Honest Templates Multiplied with Linux"],
[1]]],

[["Unde este folosit JavaScript?"],
[["a. Aplicații web"],
["b. Aplicații desktop"],
["c. Aplicații mobile"],
["d. Toate răspunsurile sunt corecte"],
[3]]],

[["Care dintre următoarele sunt CSS Preprocessors?"],
[["a. Sass"],
["b. Less"],
["c. Stylus"],
["d. Toate răspunsurile sunt corecte"],
[3]]],

[["Ce este un Framework?"],
[["a. Este un fel special de editor pentru crearea de programe"],
["b. Tip de server special"],
["c. Acesta este domeniul de aplicare al lucrărilor care trebuie realizate în cadrul proiectului"],
["d. Este o abstractizare care oferă funcționalitate generală și poate fi modificată prin cod suplimentar"],
[3]]],

[["Cum se numește procesul în care ideile sunt transmise rapid înainte și înapoi de la designer la developer și înapoi, pentru întregul ciclu de development?"],
[["a. The Hot Tomato Process"],
["b. The Hot Paprika Process"],
["c. The Hot Potato Process"],
["d. Nici un răspuns nu este corect"],
[2]]],

[["Cum puteți scrie o funcție anonimă în JS?"],
[["a. function(a) { return a \* 5; }"],
["b. function foo(a) { return a \* 5; }"],
["c. function< anonymous>(a) { return a \* 5; }"],
["d. function SuperSecretName(a) { return a \* 5; }"],
[0]]],

[["Ce este programarea orientată pe obiecte?"],
[["a. O paradigmă de programare"],
["b. Programare compusă cu figuri geometrice"],
["c. Bucată de date unică sau multiplă"],
["d. Funcție care creează un obiect"],
[0]]],

[["Care sunt valorile implicite ale parametrilor?"],
[["a. Valoarea implicită returnată de funcție"],
["b. Setări implicite ale clasei"],
["c. Valorile implicite ale funcției, astfel încât nu trebuie să îi specificăm toți parametrii cu fiecare apel"],
["d. O notație mai scurtă pentru funcții"],
[2]]],

[["Care sunt responsabilitățile frontendului?"],
[["a. Aspectul documentului"],
["b. Trimiterea de cereri către backend și gestionarea răspunsurilor de la acesta"],
["c. Programarea interacțiunii cu utilizatorii"],
["d. Toate răspunsurile sunt corecte"],
[3]]],

[["Ce este un “design pattern” în dezvoltarea de software?"],
[["a. Model de tendință în lumea modei"],
["b. Proiectare temă într-un editor de programare"],
["c. Soluție generală reutilizabilă pentru o problemă comună"],
["d. Este un model pentru interfața cu utilizatorul unei aplicații"],
[2]]],

[["Ce este un container flexibil?"],
[["a. Definește coloanele și rândurile gridului"],
["b. Specifică dimensiunea liniilor gridului"],
["c. O prescurtare pentru spațiul de rând și spațiul de coloană"],
["d. Un container care conține elementele pe care urmează să le formatăm"],
[3]]],

[["Ce face funcția „console.log ()”?"],
[["a. Afișează text în consolă"],
["b. Controlează comportamentul consolei"],
["c. Afișează istoricul jurnalului consolei"],
["d. Conectează utilizatorul la consolă"],
[0]]],

[["Care este semnificația abrevierii „DOM”?"],
[["a. Database Oriented Model"],
["b. Dynamic Opened Mobile"],
["c. Document Object Model"],
["d. Decentralized Organization of Malaysia"],
[2]]],

[["De ce aveți nevoie pentru instalarea unui CMS?"],
[["a. Server și domeniu"],
["b. Un certificat special"],
["c. Minim două monitoare"],
["d. Un tip special de browser web"],
[0]]],

[["Ce este NPM?"],
[["a. Un manager de pachete implicit pentru module și biblioteci de Node JS"],
["b. Una dintre marcajele folosite în paginile cu handicap"],
["c. Un instrument pentru a verifica erorile în cod"],
["d. Un brand care produce aparate de bucătărie"],
[0]]],

[["Ce este MVC?"],
[["a. Bibliotecă JavaScript"],
["b. Un tip special de browser web"],
["c. Editor de programare avansat"],
["d. Model de proiectare software"],
[3]]],

[["Care dintre următoarele este o directivă structurală în Angular?"],
[['a. \*ngIf="student"'],
['b. [ngClass]="{\'blue\'=true, \'yellow\'=false}"'],
['c. [style.color]="blue"'],
['d. [(ngModel)]="firstName"'],
[0]]],

[["Ce este testarea automată?"],
[["a. Testerii folosesc scripturi de testare care compară rezultatele reale și cele așteptate"],
["b. Un proces în care testerii examinează diferite caracteristici ale unei aplicații fără a utiliza instrumente sau scripturi"],
["c. Este o fază în care se colectează toate detaliile necesare despre produs"],
["d. Pregătirea mediului de testare, colectarea de cazuri de testare, cercetarea caracteristicilor produsului și a testelor de caz"],
[0]]],

[["Ce înseamnă HTML?"],
[["a. Hydro Tesla Markdown List"],
["b. HyperText Markup Language"],
["c. Hipster Technology Making Lasagne"],
["d. Honest Templates Multiplied with Linux"],
[1]]],

[["Ce limbaje de programare sunt utilizate cel mai frecvent de dezvoltatorii front-end?"],
[["a. HTML, PHP, Python"],
["b. Java, C++, CSS"],
["c. HTML, CSS, JavaScript"],
["d. Ada, Assembler, SQL"],
[2]]],

[["Care sunt avantajele utilizării preprocesoarelor CSS?"],
[["a. Permit crearea mai rapidă și mai ușoară a codului CSS"],
["b. Code nesting,care permite descrierea structurii HTML"],
["c. Permite reutilizarea codului creând variabile și mixin-uri"],
["d. Toate răspunsurile sunt corecte"],
[3]]],

[["Ce este CSS Framework?"],
[["a. Un set de fișiere de stil predefinite"],
["b. Un tip de CSS preprocessor"],
["c. Sintaxa și proprietățile limbajului CSS"],
["d. Numele motorului de redare CSS din browser"],
[0]]],

[["Care dintre următoarele sunt aplicații care îi ajută pe programatori și designeri grafici în munca lor?"],
[["a. Spotify, Google Translator, Alcohol 120%"],
["b. FileZilla, VLC, AdGuard"],
["c. Zeplin, InVision, Adobe XD"],
["d. phpStorm, Visual Studio Code, Notepad++"],
[2]]],

[["Ce este structural programming?"],
[["a. O paradigmă de programare bazată pe împărțirea codului în proceduri și blocuri aranjate ierarhic"],
["b. Paradigma de programare, în care programele sunt definite de obiecte"],
["c. Programarea în echipe care are structurile potrivite"],
["d. Programare care utilizează un sistem de control al versiunilor"],
[0]]],

[["Care este caracteristica programării orientate pe obiecte?"],
[["a. Eficient"],
["b. Reutilizabil"],
["c. Scalabil"],
["d. Toate răspunsurile sunt corecte"],
[3]]],

[["Ce înseamnă această notație: var {brand, model, year} = car;"],
[["a. Aceasta este definiția unui obiect"],
["b. Aceasta atribuie întregul conținut al variabilei “car” proprietăților obiectului"],
["c. Proprietățile obiectului “car” vor fi extrase în 3 variabile"],
["d. O astfel de notație nu există în JS"],
[2]]],

[["Ce este un server?"],
[["a. O persoană care servește în timpul unui joc de volei"],
["b. Un computer cu software pentru a gestiona cererile și a da răspunsuri"],
["c. Un bucătar care servește mâncăruri"],
["d. Un browser web care afișează cod"],
[1]]],

[["Care dintre următoarele sunt modele de proiectare(design patterns)?"],
[["a. Bootstrap, Bulma, Tailwind CSS"],
["b. Singleton, Decorator, MVC"],
["c. Vue, React, Angular"],
["d. Figma, Illustrator, Photoshop"],
[1]]],

[["Care este numele unei funcții JS care poate ajuta la depanare?"],
[["a. console.log()"],
["b. debug()"],
["c. log()"],
["d. find()"],
[0]]],

[["Cum se găsește o secvență de 3 numere folosind expresii regulate?"],
[["a. /[a-z]+/"],
["b. /[0-9]+/"],
["c. /[0-9]{3}/"],
["d. /(.\*)/"],
[2]]],

[["Care sunt avantajele WordPress-ului?"],
[["a. Gratuit cu cod sursă deschisă"],
["b. Comunitate mare"],
["c. Abilitatea de a crea orice fel de site"],
["d. Toate răspunsurile sunt corecte"],
[3]]],

[["Care dintre următoarele sunt instrumente de dezvoltare pentru JS?"],
[["a. Less, Sass, Stylus"],
["b. Webpack, Grunt, npm"],
["c. Sarius, Taco, Hades"],
["d. uBlock, ZSH, Bash"],
[1]]],

[["Ce este Angular CLI?"],
[["a. O interfață de linie de comandă care ajută dezvoltatorii să creeze proiecte noi"],
["b. Un plugin pentru browser care ajută la depanare"],
["c. Un plugin pentru editor care vă ajută să scrieți cod"],
["d. Numele celei mai recente versiuni de Angular"],
[0]]],

[["În ce limbaj este scris framework-ul angular?"],
[["a. CoffeScript"],
["b. JavaScript"],
["c. TypeScript"],
["d. SuperScript"],
[2]]],

[["Ce înțelegeți prin testarea software-ului?"],
[["a. Testarea ocazională a aplicației de către dezvoltatorul care creează funcționalitatea"],
["b. Test de funcționalitate a aplicației dezvoltate de client"],
["c. Testarea performanței aplicației"],
["d. Un proces de validare care confirmă faptul că un sistem funcționează conform cerințelor companiei"],
[3]]],

[["Ce este CSS Preprocessor?"],
[["a. Un instrument care extinde funcționalitatea vanilla CSS"],
["b. Acesta este motorul browserului care redă proprietăți CSS"],
["c. Componenta computerului pe care o cumpărați pentru a deveni dezvoltator web"],
["d. Nu există așa ceva"],
[0]]],

[["De ce utilizează programatorii framework-urile?"],
[["a. Pentru că le permit să se concentreze pe funcționalități de nivel înalt"],
["b. Acestea oferă cea mai înaltă performanță software"],
["c. Pentru că nu pot programa fără ele"],
["d. Fac codificarea mai obositoare și mai lentă"],
[0]]],

[["De ce sunt utile aplicațiile precum Zeplin sau Figma pentru dezvoltatori?"],
[["a. Scrieți automat cod pentru grafica pe care designerul a proiectat-o, astfel încât să nu fie nevoie să programați"],
["b. Generați automat specificații, active și fragmente de cod din modele"],
["c. Permiteți comunicarea gratuită de text, voce și video cu echipa de grafică"],
["d. Aceste aplicații elimină orice neînțelegeri dintre echipe"],
[1]]],

[["Ce expresii sunt responsabile pentru afirmațiile condiționate?"],
[["a. indexOf"],
["b. break, exit"],
["c. if, switch"],
["d. console.log"],
[2]]],

[["Ce limbaje permit programarea orientată pe obiecte?"],
[["a. Java"],
["b. PHP"],
["c. JavaScript"],
["d. Toate răspunsurile sunt corecte"],
[3]]],

[["Ce activează proprietatea Prototype din JavaScript?"],
[["a. Vă permite să utilizați moștenirea"],
["b. Activează prototiparea aplicației"],
["c. Nu există așa ceva în JS"],
["d. Activează modul dezvoltator adevărat"],
[0]]],

[["În ce două ramuri separate a evoluat dezvoltarea web?"],
[["a. Webmasters și Web Graphics"],
["b. Front-end și Back-end"],
["c. Iubitori și haterii de JS"],
["d. Persoane cu și fără blocare publicitară"],
[1]]],

[["Ce este o revizuire a codului?"],
[["a. Revizuirea publică a codului sursă de către critici cunoscuți"],
["b. O revizuire sistematică a codului sursă"],
["c. Evaluați singur codul sursă"],
["d. Acordați codului sursă o notă de la 1 la 10"],
[1]]],

[["Ce sunt articolele flex?"],
[["a. Un container care conține elementele pe care urmează să le formatăm"],
["b. Specificați dimensiunea oricărei piste de grilă generate automat"],
["c. O prescurtare pentru spațiul de rând și spațiul de coloană"],
["d. Elemente ale căror poziții reciproce pot fi definite utilizând flexbox pe container"],
[3]]],

[["Ce face funcția \"console.log()\" ?"],
[["a. Afișează text în consolă"],
["b. Controlează comportamentul consolei"],
["c. Afișează istoricul jurnalului consolei"],
["d. Conectați utilizatorul la consolă"],
[0]]],

[["Cum se înlocuiește un model găsit cu un alt text în JS?"],
[["a. regexp.test(str)"],
["b. str.match(regexp)"],
["c. str.replace(regexp, replacement)"],
["d. str\_replace(regexp, replacement, str)"],
[2]]],

[["WordPress a început inițial ca un sistem de blog, dar datorită ... a devenit universal. Ce se ascunde în spatele punctelor?"],
[["a. Temelor"],
["b. Plugin-urilor"],
["c. Utilizatorilor"],
["d. Postărilor"],
[1]]],

[["Ce este Node.js?"],
[["a. Cadru pentru scrierea aplicațiilor mobile în J"],
["b. Un editor conceput în principal pentru scrierea codului JavaScript"],
["c. O bibliotecă JavaScript pentru navigarea în arborele DOM"],
["d. Mediu de execuție pentru dezvoltarea aplicațiilor de pe server în JavaScript"],
[3]]],

[["Care este caracteristica Single Page Application?"],
[["a. Nu trebuie să reîncărcați o pagină"],
["b. Este stocat în memoria dispozitivului"],
["c. Este complet receptiv"],
["d. Permite utilizarea notificărilor push"],
[0]]],

[["Ce este o componentă în Angular?"],
[["a. Definește modul în care clasa este procesată de framework"],
["b. Este un mecanism de grupare a directivelor conexe"],
["c. Reprezintă o parte specifică a interfeței cu utilizatorul"],
["d. Vă ajută să începeți rapid dezvoltarea de aplicații angular"],
[2]]],

[["Care dintre următoarele tipuri de testare software este corectă?"],
[["a. Raportarea"],
["b. Testarea funcțională"],
["c. Testarea clientului"],
["d. Planificarea"],
[1]]],

[["Care dintre următoarele sunt CSS Preprocessors?"],
[["a. Sass"],
["b. Less"],
["c. Stylus"],
["d. Toate răspunsurile sunt corecte"],
[3]]],

[["Ce este Bootstrap CSS?"],
[["a. Cel mai popular framework CSS din lume"],
["b. Un preprocesor CSS"],
["c. Ultima versiune a CSS"],
["d. Cheat Engine pentru Counter Strike Source"],
[0]]],

[["Ce este cel mai important atunci când vine vorba de colaborarea dintre un dezvoltator de software și un designer?"],
[["a. Explicarea fiecărui aspect al codului"],
["b. Comunicarea și partajarea activității din timp și des"],
["c. Așteptați cu feedback până când proiectul este finalizat"],
["d. Începeți implementarea proiectelor cât mai curând posibil"],
[1]]],

[["Ce este o funcție în JavaScript?"],
[["a. Fragmente de cod denumite, destinate să îndeplinească anumite sarcini"],
["b. Operator matematic"],
["c. Tipul variabilelor"],
["d. Întregul cod al programului"],
[0]]],

[["Ce este o proprietate?"],
[["a. Entitate de bază a OOP"],
["b. Paradigma de programare"],
["c. Variabilă în interiorul unui obiect"],
["d. Categoria unui obiect"],
[2]]],

[["Ce este un obiect Promise în JS?"],
[["a. Este un obiect care promite să returneze întotdeauna rezultatul corect al unei acțiuni"],
["b. Reprezintă finalizarea cu succes (sau eșecul) unei operații asincrone și valoarea rezultată a acesteia"],
["c. Acesta este un obiect special care vă permite să moșteniți proprietățile și metodele clasei"],
["d. Este o funcție care evaluează codul JavaScript reprezentat ca un șir"],
[1]]],

[["Care dintre următoarele sunt concepte utile de proiectare?"],
[["a. KISS"],
["b. DRY"],
["c. SOLID"],
["d. Toate răspunsurile sunt corecte"],
[3]]],

[["De ce este responsabilă regula \"@font-face\"?"],
[["a. Vă permite să atașați fonturi personalizate in stilul vostru"],
["b. Setează stilul fontului"],
["c. Vă permite să adăugați decorațiuni la un font"],
["d. Face ca fontul utilizat să fie receptiv"],
[0]]],

[["Ce arată panoul „Sources” din Instrumentele pentru dezvoltatori din browser?"],
[["a. Elemente legate de rețea"],
["b. Toate fișierele utilizate de aplicația noastră"],
["c. Consola"],
["d. Elemente legate de siguranță"],
[1]]],

[["Care dintre următoarele este cel mai mare dezavantaj al WordPress?"],
[["a. Cerințe reduse de găzduire"],
["b. Documentare extinsă și detaliată"],
["c. Codul este open source, dar există o taxă pentru utilizarea acestuia"],
["d. Cel mai frecvent atacat CMS"],
[3]]],

[["Ce sunt pachetele de Node.js?"],
[["a. Fișiere sau directoare care sunt descrise de un package.json"],
["b. Obiecte, care sunt disponibile în toate modulele"],
["c. Worker threads"],
["d. Grupuri de obiecte DOM"],
[0]]],

[["Ce înseamnă SPA?"],
[["a. Socialist Party of Australia"],
["b. Single Page Application"],
["c. Supreme People's Assembly"],
["d. Software Publishers Association"],
[1]]],

[["Ce este un modul în Angular?"],
[["a. Definește modul în care clasa este procesată de framework"],
["b. Este un mecanism de grupare a funcționalităților mari și conexe"],
["c. Reprezintă o parte specifică a interfeței cu utilizatorul"],
["d. Un mecanism care face o modalitate de partajare a datelor între o componentă și șablonul acesteia"],
[1]]],

[["De ce este responsabilă testarea performanței?"],
[["a. Stabilește robustețea software-ului evaluând dacă funcționează dincolo de operarea obișnuită"],
["b. Aceasta testează performanța sistemului încărcând baza de date într-un volum crescut de date"],
["c. Verifică dacă sistemul este protejat împotriva atacurilor bruște sau deliberate din surse interne și externe"],
["d. Acest test examinează performanța sau viteza aplicației sub sarcina de lucru necesară"],
[3]]],

[["De ce aveți nevoie pentru a deschide un document HTML?"],
[["a. Un program grafic special, precum Photoshop"],
["b. Un plug-in potrivit pentru browserul web"],
["c. Doar un browser web"],
["d. Editor de programare avansat"],
[2]]],

[["Cum sunt create variabilele în Sass?"],
[["a. var foo = #AAF700;"],
["b. $foo = #AAF700;"],
["c. {{ foo = #AAF700 }}"],
["d. foo = str(#AAF700)"],
[1]]],

[["Care sunt practicile bune de a lucra împreună cu un designer?"],
[["a. Fii atent la detalii"],
["b. Discutați deciziile de proiectare"],
["c. Reîncadrați cerințele ca ipoteze care ar trebui validate înainte de implementarea finală"],
["d. Toate răspunsurile sunt corecte"],
[3]]],

[["În ce paradigme de programare se încadrează JavaScript?"],
[["a. structurat"],
["b. funcţional"],
["c. orientat spre obiect"],
["d. Toate răspunsurile sunt corecte"],
[3]]],

[["Ce este o metodă?"],
[["a. Entitate de bază a OOP"],
["b. Paradigma de programare"],
["c. O funcție din interiorul unui obiect"],
["d. Categoria unui obiect"],
[2]]],

[["Ce este asincronicitatea?"],
[["a. Un mecanism care permite efectuarea anumitor sarcini în „fundal” fără a bloca alte sarcini"],
["b. Titlul noului film fiind realizat de creatorii The Matrix."],
["c. Mecanismul executării codului programului rând cu rând"],
["d. Mecanismul implicit în care funcționează JavaScript"],
[0]]],

[["Ce este un client pe web?"],
[["a. La fel ca în realitate - cumpărătorul produselor noastre"],
["b. Un browser web care afișează cod de pe server"],
["c. Acesta reprezintă interfața instrumentului de linie de comandă"],
["d. Un computer cu software pentru a gestiona cererile și a da răspunsuri"],
[1]]],

[["Ce este așa-numitul cod curat?"],
[["a. Acesta este un tip special de cod care există doar în anumite limbaje de programare"],
["b. O abordare în care scriem cod lizibil pentru noi și pentru ceilalți"],
["c. Este o tehnică care implică curățarea codului sursă cu un dispozitiv de curățare"],
["d. Acesta este codul pe care îl scrieți folosind numai vocale"],
[1]]],

[["Cum se rotunjesc laturile unui element din CSS?"],
[["a. Utilizați proprietatea „rotundă”"],
["b. Utilizați proprietatea „la colț”"],
["c. Utilizați proprietatea „flex”"],
["d. Utilizați proprietatea „border-radius”"],
[3]]],

[["Ce face breakpoint în timpul depanării?"],
[["a. Distruge tot codul sursă al aplicației"],
["b. Indică lucruri importante"],
["c. Întrerupe executarea codului"],
["d. Stabilește puncte de cotitură"],
[2]]],

[["Cum se selectează un element HTML cu ID-ul \"form\"?"],
[["a. document.getElementsByName(\"form\")"],
["b. document.getElementById(\"form\")"],
["c. document.getElementsByTagName(\"form\")"],
["d. document.getElementsByClassName(\"form\")"],
[1]]],

[["De ce aveți nevoie pentru instalarea CMS?"],
[["a. Server și domeniu"],
["b. Un certificat special"],
["c. Minim două monitoare"],
["d. Un tip special de browser web"],
[0]]],

[["Ce înseamnă „NPM”?"],
[["a. Network Promising Manual"],
["b. Nintendo Power Master"],
["c. New Portland Menu"],
["d. Node Package Manager"],
[3]]],

[["Cum declarați un tip variabil în TypeScript?"],
[["a. let foo< number> = 12345;"],
["b. number foo = 12345;"],
["c. let foo: number = 12345;"],
["d. let foo[ number ] = 12345;"],
[2]]],

[["Ce este data-binding în Angular?"],
[["a. Definește modul în care clasa este procesată de framework"],
["b. Este un mecanism de grupare a funcționalităților mari și conexe"],
["c. Reprezintă o parte specifică a interfeței cu utilizatorul"],
["d. Un mecanism care face o modalitate de partajare a datelor între o componentă și template-ul acesteia"],
[3]]],

[["De ce este responsabilă testarea utilizabilității?"],
[["a. Explorează ușurința utilizatorului final în ceea ce privește învățarea, operarea și pregătirea intrărilor și a rezultatelor"],
["b. Aceasta testează performanța sistemului încărcând baza de date într-un volum crescut de date"],
["c. Verifică dacă sistemul este protejat împotriva atacurilor bruște sau deliberate din surse interne și externe"],
["d. Acest test examinează performanța sau viteza aplicației sub sarcina de lucru necesară"],
[0]]],

[["Ce caractere folosește HTML?"],
[["a. “<” și “>”"],
["b. “{“ și “}“"],
["c. “[“ și “]”"],
["d. “@” și “#”"],
[0]]],

[["Ce sunt diagramele de flux (diagrame bloc)?"],
[["a. O reprezentare schematică a unui algoritm"],
["b. Vă permite să determinați numărul exact de rezidenți aflați într-un apartament"],
["c. Acestea sunt pur și simplu grafice, precum diagrame"],
["d. Diagrama care arată ordinea clicurilor în aplicație"],
[0]]],

[["Ce este un selector părinte în Sass?"],
[["a. Acesta este un selector special folosit pentru a stiliza numai părinții unui element HTML"],
["b. Este o funcție specială pe care o creăm ca părinte pentru selector"],
["c. Este un selector special utilizat în selectoarele nested pentru a se referi la selectorul exterior"],
["d. Nu există așa ceva"],
[2]]],

[["Care sunt avantajele utilizării unui framework?"],
[["a. Dezvoltare software mai rapidă"],
["b. Ajută la evitarea duplicării codului"],
["c. Are funcționalitate parțial gata pregătită"],
["d. Toate răspunsurile sunt corecte"],
[3]]],

[["Cum se numește procesul în care ideile sunt transmise rapid înainte și înapoi de la proiectant la dezvoltator și înapoi, pentru întregul ciclu de creare a produsului?"],
[["a. The Hot Tomato Process"],
["b. The Hot Paprika Process"],
["c. The Hot Potato Process"],
["d. Nici un răspuns nu este corect"],
[2]]],

[["Ce este o funcție anonimă?"],
[["a. O funcție fără nume"],
["b. O funcție care nu vrea să-și dezvăluie numele"],
["c. O funcție secretă pe care doar câțiva o cunosc"],
["d. O funcție care se teme să-și dezvăluie numele"],
[0]]],

[["Ce este o clasă?"],
[["a. Entitate de bază a OOP"],
["b. Paradigma de programare"],
["c. Variabilă în interiorul unui obiect"],
["d. Categoria unui obiect"],
[3]]],

[["În mod implicit, JavaScript este sincron. Ce înseamnă asta?"],
[["a. Codul se execută în fundal, independent de alte sarcini"],
["b. Codul este executat linie cu linie"],
["c. Aplicația JS se sincronizează cu serverele dezvoltatorilor"],
["d. JS returnează două stări, în funcție de succesul sau eșecul operațiunii noastre"],
[1]]],

[["La ce lucrează un developer de front-end?"],
[["a. Construiește soluții pe partea de server"],
["b. Scrie cod numai în HTML"],
["c. Se ocupă cu crearea infrastructurii de rețea"],
["d. Lucrează la tot ceea ce vine de la server catre aplicația client"],
[3]]],

[["Ce sunt standardele de denumire?"],
[["a. Acestea sunt standardele după care vă numiți computerul"],
["b. Standarde restrictive pentru care încetezi să mai fii programator"],
["c. Standarde care acoperă modele generale pentru specificarea numelor și identificatorilor pe tot parcursul proiectului"],
["d. Un set de reguli despre cum ar trebui să îi numiți colegii dvs."],
[2]]],

[["Cum se adaugă o umbră textului în CSS?"],
[["a. Utilizați proprietatea „text-shadow”"],
["b. Utilizați proprietatea „box-shadow”"],
["c. Utilizați proprietatea „font-shadow”"],
["d. Folosiți proprietatea „umbră”"],
[0]]],

[["Ce este depanarea/debug-ul?"],
[["a. Acesta este procesul prin care clientul interoghează serverul"],
["b. Găsirea erorilor și încercarea de a le remedia"],
["c. Găsirea de bug-uri și prepararea cinei cu ele"],
["d. Funcție specială JavaScript pentru crearea codului asincron"],
[1]]],

[["Cum se creează un nou element HTML?"],
[["a. document.appendChild(“div”)"],
["b. body.insertBefore(“div”, root)"],
["c. document.querySelector(\"div\")"],
["d. document.createElement(\"div\")"],
[3]]],

[["Ce înseamnă „CMS”?"],
[["a. Construction and Management Simulation"],
["b. Color Management System"],
["c. Content Management System"],
["d. Cryptographic Message Syntax"],
[2]]],

[["Ce este TypeScript?"],
[["a. Cadrul JavaScript"],
["b. Limbaj de programare, un superset de JavaScript"],
["c. Bibliotecă JavaScript"],
["d. Plug-in Visual Studio Code"],
[1]]],

[["Ce este un template în Angular?"],
[["a. Definește modul în care clasa este procesată de către framework"],
["b. Este un mecanism de grupare a funcționalităților mari și conexe"],
["c. Inserează un comportament suplimentar în codul HTML"],
["d. Conține codul HTML care trebuie afișat pe ecranul utilizatorului"],
[3]]],

[["De ce este responsabil testarea de securitate?"],
[["a. Stabilește robustețea software-ului evaluând dacă funcționează dincolo de operarea obișnuită"],
["b. Aceasta testează performanța sistemului încărcând baza de date într-un volum crescut de date"],
["c. Verifică dacă sistemul este protejat împotriva atacurilor bruște sau deliberate din surse interne și externe"],
["d. Acest test examinează performanța sau viteza aplicației sub sarcina de lucru necesară"],
[2]]],

[["Ce permite HTML?"],
[["a. Inserați imagini"],
["b. Inserați videoclipuri"],
["c. Creați tabele"],
["d. Toate răspunsurile sunt corecte"],
[3]]],

[["Care este semnul „at-rule” în Sass?"],
[["a. &"],
["b. %"],
["c. @"],
["d. $"],
[2]]],

[["Care dintre următoarele sunt framework-uri CSS?"],
[["a. Angular, Vue, React,"],
["b. Bootstrap, Fundation, Bulma"],
["c. Laravel, Symfony, CodeIgniter"],
["d. Spring, Struts, Hibernate"],
[1]]],

[["Inspect în Zeplin vă permite să vedeți anumite informații despre elementul selectat. Ce fel de specificații puteți vedea pe panoul din partea dreaptă?"],
[["a. Dimensiunea tipului, înălțimea liniei, spațierea, culoarea"],
["b. Buton Copiere care salvează textul în clipboard"],
["c. Fragment de cod în CSS (sau SCSS, Sass etc.)"],
["d. Toate răspunsurile sunt corecte"],
[3]]],

[["Ce este un constructor?"],
[["a. Entitate de bază a OOP"],
["b. Paradigma de programare"],
["c. Variabilă în interiorul unui obiect"],
["d. Funcție care creează un obiect"],
[3]]],

[["Cum se scrie o clasă în JavaScript?"],
[["a. function classCar() {...}"],
["b. class Car {...}"],
["c. new Car(...)"],
["d. var car \_ => {...}"],
[1]]],

[["La ce lucrează un developer de back-end?"],
[["a. Scrie cod doar în HTML"],
["b. Se ocupă cu crearea infrastructurii de rețea"],
["c. Construiește soluții pe partea de server"],
["d. Lucrează cu tot ceea ce vine de la server la aplicația client"],
[2]]],

[["Ce este ESLint?"],
[["a. Verificator ortografic spaniol"],
["b. Un instrument care analizează codul sursă pentru erori de programare"],
["c. Program pentru formatarea automată a codului"],
["d. Eveniment pe Liga Sporturilor Electronice"],
[1]]],

[["Pentru a trece lin de la o culoare de fundal la alta, ce proprietate CSS veți utiliza?"],
[["a. transition"],
["b. transform"],
["c. box-shadow"],
["d. background"],
[0]]],

[["Cum se numește procesul de găsire și corectare a erorilor?"],
[["a. dewormsing"],
["b. deleting"],
["c. cockroaching"],
["d. debugging"],
[3]]],

[["Cum gestionați evenimentul de click pe element?"],
[["a. x.whenClick = function() {...}"],
["b. x.onclick = function() {...}"],
["c. x.clicked(() => {...})"],
["d. x.on(‘click’, function() {...}"],
[1]]],

[["Ce este WordPress?"],
[["a. Editor de programare"],
["b. Plug-in pentru browser"],
["c. Cel mai popular CMS din lume"],
["d. Sistem de operare în țările asiatice"],
[2]]],

[["Cum se instalează un pachet într-un proiect folosind NPM?"],
[["a. npm install < package-name>"],
["b. npm build < package-name>"],
["c. npm audit < package-name>"],
["d. npm link < package-name>"],
[0]]],

[["Cum arată interpolarea șirurilor în Angular?"],
[["a. < button (click)=\"clickHandler()\">Click Me< /button>"],
["b. < p>Hello, my name is {{ name }}!< /p>"],
["c. < img [src]=\"imageURL\" [alt]=\"imageAlt\">"],
["d. < p \*ngIf=\"product.description\">Lorem ipsum…< /p>"],
[1]]],

[["Ce două moduri de testare software există?"],
[["a. Rapid și lent"],
["b. Exact și inexact"],
["c. Manual și automat"],
["d. Din partea dezvoltatorului și a clientului"],
[2]]],

[["Ce proprietate CSS este responsabilă pentru tipul de font?"],
[["a. font-style"],
["b. font-family"],
["c. font-size"],
["d. font-weight"],
[1]]],

[["Ce face funcția „alert ()” în JavaScript?"],
[["a. Lansează o fereastră pop-up cu textul dorit"],
["b. Declanșează o alarmă pe computer"],
["c. Lansează o fereastră care solicită vârsta utilizatorului"],
["d. Avertizează împotriva virușilor"],
[0]]],

[["Ce face regula „@import” în Sass?"],
[["a. Încarcă mixins, funcții și variabile din alte fișiere SASS"],
["b. Acesta definește o bucată reutilizabilă de cod SASS"],
["c. Importă conținutul stylesheet-ului extern în cel curent"],
["d. Vă permite să definiți o funcție"],
[2]]],

[["Ce este ”responsive web design”?"],
[["a. Este o abordare care permite site-urilor web să redea pe toate dispozitivele, adaptându-se automat la ecran"],
["b. Un site web care interacționează ca urmare a acțiunilor efectuate de utilizator"],
["c. Modul în care reacționează politicienii la apelurile publice"],
["d. Este genul de design web care implică asumarea responsabilității pentru conținutul pe care îl creați"],
[0]]],

[["Ce instrument este cel mai bun atunci când vine vorba de predarea proiectelor la implementare?"],
[["a. Invision"],
["b. Zeplin"],
["c. Avocode"],
["d. Nu există un răspuns corect. Fiecare echipă și proiect are nevoi diferite"],
[3]]],

[["Care sunt componentele fundamentale ale programării structurate?"],
[["a. Structuri de control"],
["b. Subrutine (funcții)"],
["c. Blocuri de cod"],
["d. Toate răspunsurile sunt corecte"],
[3]]],

[["Cum arată “arrow function”?"],
[["a. func(a, b) -> { a + b };"],
["b. (a, b) => a + b;"],
["c. {a, b} -> a + b;"],
["d. function(a, b) { a + b };"],
[1]]],

[["Ce este AJAX?"],
[["a. Un club de fotbal profesionist olandez cu sediul la Amsterdam, care joacă în Eredivisie"],
["b. Un troian carbonic Jupiter din lagărul grecesc, cu un diametru de aproximativ 83 de kilometri"],
["c. Acesta înseamnă JavaScript și XML asincron și permite clientului să comunice cu serverul în mod asincron"],
["d. Numele purtat de opt nave ale Marinei Regale Britanice"],
[2]]],

[["Ce este Prettier?"],
[["a. Programul care vă face desktopul mai frumos"],
["b. Un instrument pentru formatarea automată a codului"],
["c. O aplicație pentru telefonul dvs. care vă îmbunătățește aspectul"],
["d. Program care analizează codul sursă pentru erori de programare"],
[1]]],

[["Pentru a scrie stiluri pentru dispozitive cu ecrane diferite, ce veți folosi?"],
[["a. @font-face"],
["b. @import"],
["c. @keyframes"],
["d. @media"],
[3]]],

[["Ce este un “regular expression”?"],
[["a. O secvență de caractere care specifică un model de căutare"],
["b. Este o frază pe care oamenii o folosesc adesea atunci când vorbesc"],
["c. Aceasta este expresia care, printre altele, alcătuiește sintaxa JS"],
["d. Acesta este numele corect pentru un selector în CSS"],
[0]]],

[["Ce este o structură de date?"],
[["a. Acestea sunt datele care alcătuiesc variabila"],
["b. Acesta este aranjamentul datelor din aplicație"],
["c. O formă specializată de organizare, prelucrare și recuperare a datelor"],
["d. Structura și structura codului"],
[2]]],

[["Pentru ce folosim CMS?"],
[["a. Website-uri"],
["b. E-Commerce"],
["c. Aplicații web și mobile"],
["d. Toate răspunsurile sunt corecte"],
[3]]],

[["Ce este Webpack?"],
[["a. Framework JavaScript"],
["b. Pachet de module statice pentru aplicații JavaScript moderne"],
["c. Bibliotecă JavaScript"],
["d. O extensie de browser pentru dezvoltatori"],
[1]]],

[["De ce este responsabil un controler în modelul MVC?"],
[["a. Descrie ceea ce este afișat, conține date despre aplicație"],
["b. Descrie modul în care sunt afișate datele modelului utilizând șabloanele de vizualizare"],
["c. Descrie modul în care partea modelului și partea vizualizată se conectează între ele"],
["d. Automatizează comunicarea între model și controler"],
[2]]],

[["Care dintre următoarele este o directivă structurată în Angular?"],
[["a. \*ngIf=\"student\""],
["b. [ngClass]=\"{'blue'=true, 'yellow'=false}\""],
["c. [style.color]=\"blue\""],
["d. [(ngModel)]=\"firstName\""],
[0]]],

[["Ce este testarea manuală?"],
[["a. Testerii folosesc scripturi de testare care compară rezultatele reale și cele așteptate"],
["b. Un proces în care testerii examinează diferite caracteristici ale unei aplicații fără a utiliza instrumente sau scripturi"],
["c. Este o fază în care colectați toate detaliile necesare despre produs"],
["d. Pregătirea mediului de testare, colectarea cazurilor de testare, cercetarea caracteristicilor produsului și a cazurilor de testare"],
[1]]],

[["Cum arată tag-ul de tip al documentului HTML?"],
[["a. < !'DOCTYPE html'>"],
["b. < body>"],
["c. < footer>"],
["d. < meta type=”text/xml”>"],
[0]]],

[["Care dintre următoarele este un exemplu de algoritm?"],
[["a. Rețetă de gătit"],
["b. Trecerea de la A la B"],
["c. Suma a două numere"],
["d. Toate răspunsurile sunt corecte"],
[3]]],

[["Ce „reguli” vă permit să creați condiții și bucle în Sass?"],
[["a. @use, @mixin, @import"],
["b. @if, @while, @for"],
["c. @error, @warn, @debug"],
["d. @forward, @function"],
[1]]],

[["Ce este un sistem de rețea?"],
[["a. O tehnologie pentru a vă înconjura în siguranță casa"],
["b. Acesta este numele sistemului de operare pentru PC-uri"],
["c. O structură care cuprinde o serie de linii orizontale și verticale, utilizate pentru aranjarea conținutului"],
["d. Denumire comună pentru tabele în HTML"],
[2]]],

[["De ce să optimizați imaginile înainte de a le plasa într-o aplicație web?"],
[["a. Imaginile optimizate câștigă calitate și arată mai bine"],
["b. Nu se pot adăuga alte imagini decât cele optimizate"],
["c. Astfel de imagini au cel mai bun UX"],
["d. Îmbunătățiți performanța aplicației, accelerați încărcarea aplicației"],
[3]]],

[["Cum se scrie un obiect în JavaScript?"],
[["a. var obj = [...];"],
["b. let obj = {...};"],
["c. const obj = ‘Object’;"],
["d. var obj = /.../;"],
[1]]],

[["Care sunt responsabilitățile backend-ului?"],
[["a. Gestionarea cererilor"],
["b. Date de procesare"],
["c. Furnizarea de răspunsuri"],
["d. Toate răspunsurile sunt corecte"],
[3]]],

[["Când se folosește un model de design?"],
[["a. Când lucrezi în echipă"],
["b. Când lucrezi singur"],
["c. Nu este niciodată o idee bună să o folosești"],
["d. Ar trebui să utilizați întotdeauna un model de design"],
[3]]],

[["Care este numele modulului CSS care vă permite să creați cu ușurință coloane și rânduri?"],
[["a. Grid Layout"],
["b. Flex"],
["c. Block"],
["d. Inline"],
[0]]],

[["Cum se numește forma scurtată a unei expresii regulate?"],
[["a. RglrXprssn"],
["b. RegEx"],
["c. ExpReg"],
["d. Nu există shortcut"],
[1]]],

[["Ce este o structură de date numită stivă?"],
[["a. O structură de date, cu elemente legate unul după altul."],
["b. O structură de date, în care adăugăm elemente pe o parte și le eliminăm de pe cealaltă parte"],
["c. O structură de date, în care adăugăm sau eliminăm elemente doar dintr-o parte"],
["d. O succesiune de elemente de un anumit tip aranjate într-o ordine specifică. Fiecare element are un indice specific"],
[2]]],

[["Care dintre CMS listate este cel mai popular din lume?"],
[["a. Joomla"],
["b. Drupal"],
["c. Squarespace"],
["d. WordPress"],
[3]]],

[["Care dintre următoarele sunt alternative la NPM?"],
[["a. ied, yarn, pnpm"],
["b. Less, Sass, Stylus"],
["c. Notepad++, VSC, webStorm"],
["d. uBlock, ZSH, Bash"],
[0]]],

[["De Ce este responsabil un model în MVC?"],
[["a. Descrie ceea ce este afișat, conține date despre aplicație"],
["b. Descrie modul în care sunt afișate datele modelului utilizând șabloanele de vizualizare"],
["c. Descrie modul în care partea modelului și partea vizualizată se conectează între ele"],
["d. Automatizează comunicarea între model și controler"],
[0]]],

[["Cum poate un copil să trimită informații unui părinte din Angular?"],
[["a. Via @Input()"],
["b. Via @Output()"],
["c. Via @Component()"],
["d. Via @NgModule"],
[1]]],

[["Ce este CSS?"],
[["a. Counter-Strike Source"],
["b. Československá Strana Socialistická"],
["c. Cascading Style Sheet"],
["d. Chinese Space Station"],
[2]]],

[["Cum se declară un tip variabil în JavaScript?"],
[["a. string hello = 'Hello, World'"],
["b. Nu se pot declara tipurile de variabile"],
["c. let hello:string = ‘Hello, World’"],
["d. var hello< string> = ‘Hello, World’"],
[1]]],

[["De ce să folosiți indentarea/nesting în Sass?"],
[["a. Vă menține codul organizat și îl face mult mai ușor de citit"],
["b. Acest lucru determină precompilarea mai rapidă a codului"],
["c. Pentru că toată lumea o face"],
["d. În caz contrar, este imposibil să scrii în Sass"],
[0]]],

[["Ce sunt componentele din cadrul Bootstrap?"],
[["a. Acestea sunt bibliotecile pe care se bazează Bootstrap"],
["b. Limba, cursurile, imaginile și tutorialele din documentația Bootstrap sunt componentele sale"],
["c. Posibilitatea de a regla automat elementele paginii la dimensiunea ecranului dispozitivului"],
["d. Acestea sunt blocuri de construcție gata făcute, care sunt incluse în Bootstrap"],
[3]]],

[["Care este scopul variabilelor din JavaScript?"],
[["a. Regiunea bazei de cod in care este valid un identificator"],
["b. Oportunitatea de a face ceva"],
["c. Responsabilitățile programatorului"],
["d. Gama de tip în care operează variabila"],
[0]]],

[["Cum să apelați un constructor de clasă în JavaScript?"],
[["a. movie('Avatar', 2009, 'James Cameron');"],
["b. new movie('Avatar', 2009, 'James Cameron');"],
["c. call movie('Avatar', 2009, 'James Cameron');"],
["d. create movie('Avatar', 2009, 'James Cameron');"],
[1]]],

[["Care metodă returnează valoarea primului element dintr-un array, care îndeplinește condiția de testare furnizată?"],
[["a. array.fill()"],
["b. array.concat()"],
["c. array.find()"],
["d. array.join()"],
[2]]],

[["Ce componente alcătuiesc principiile unui bun design?"],
[["a. Modele de design"],
["b. Formatarea și inspecția codului"],
["c. KISS, SOLID, DRY"],
["d. Toate răspunsurile sunt corecte"],
[3]]],

[["Cum definiți un container ca un grid în CSS?"],
[["a. display: grid"],
["b. display: flex"],
["c. display: block"],
["d. display: inline"],
[0]]],

[["Ce delimitator se folosește la scrierea unui RegEx în JS?"],
[["a. @...@ (at sign)"],
["b. /.../ (slash sign)"],
["c. $...$ (dollar sign)"],
["d. %...% (percent sign)"],
[1]]],

[["La ce se folosește “canvas”?"],
[["a. Element HTML care este folosit pentru redarea multimedia"],
["b. Aceasta este una dintre multele tehnici de calcul al complexității unui algoritm"],
["c. Un element HTML în care putem desena și anima cu ajutorul JS"],
["d. Acesta este unul dintre modelele de design"],
[2]]],

[["Ce înseamnă „CRUD”?"],
[["a. cooking, riding, using, dancing"],
["b. changing, recording, understanding, depending"],
["c. coding, running, unknowing, destroying"],
["d. creating, reading, updating, deleting"],
[3]]],

[["Pe care dintre următoarele instrumente le veți folosi ca module bundler?"],
[["a. Webpack"],
["b. Sass"],
["c. WordPress"],
["d. FileZilla"],
[0]]],

[["De ce este responsabilă o vizualizare în modelul MVC?"],
[["a. Descrie ceea ce este afișat, conține date despre aplicație"],
["b. Descrie modul în care sunt afișate datele modelului utilizând șabloanele de vizualizare"],
["c. Descrie modul în care partea modelului și partea vizualizată se conectează între ele"],
["d. Automatizează comunicarea între model și controler"],
[1]]],

[["Cum poate un părinte să trimită informații unui copil din Angular?"],
[["a. Via @Input()"],
["b. Via @Output()"],
["c. Via @Component()"],
["d. Via @NgModule"],
[0]]],

[["Testarea automată face testarea manuală învechită?"],
[["a. Da, testarea manuală nu mai este utilă"],
["b. Desigur, o pierdere de timp"],
["c. Depinde..."],
["d. Nu, în unele cazuti, testarea manuala este încă obligatorie"],
[3]]],

[["Cum arată sintaxa CSS?"],
[["a. div((font\_size: 12[px]));"],
["b. div { font-size: 12px; }"],
["c. < div font-size=”12px” />"],
["d. div.setFontSize = “12px”;"],
[1]]],

[["Cum să conectați mai multe string-uri împreună în JavaScript?"],
[["a. var c = a + b;"],
["b. var c = a . b;"],
["c. var c = a ~ b;"],
["d. var c = “a b”;"],
[0]]],

[["Ce face regula „@extend” în Sass?"],
[["a. Încarcă mixins, funcții și variabile din alte fișiere SASS"],
["b. Acesta definește o bucată reutilizabilă de cod SASS"],
["c. Afișează un mesaj pentru a vă ajuta să depanați codul"],
["d. Permite unei clase să extindă alta pentru a construi rapid diferite variante"],
[3]]],

[["Care este un framewrok?"],
[["a. O metodă de lucru cu anumite limitări"],
["b. Un Tip de server special"],
["c. Un instrument care vă permite să creați software și sisteme mai rapid"],
["d. Este un tip special de editor pentru crearea de programe"],
[2]]],

[["Ce este recursivitatea?"],
[["a. Recursivitatea este atunci când un program sau o funcție se apeleaza singur"],
["b. Este un fenomen când credem că am făcut deja ceva odată"],
["c. Referință la resursele programului"],
["d. Este cel mai comun format de trimitere a datelor"],
[1]]],

[["Cum să apelați metoda „info” din obiectul „movie”?"],
[["a. movie->info();"],
["b. movie.info();"],
["c. info.movie();"],
["d. movie[methods]info();"],
[1]]],

[["Cum să combinați mai multe șiruri și să le scrieți în mai multe linii?"],
[["a. Folosiți doar semnul plus „+”"],
["b. Utilizați metoda de îmbinare"],
["c. Utilizați „template literals” (backtick), de ex. `string tex`"],
["d. Nu există o astfel de posibilitate"],
[2]]],

[["Dezvoltatorii de backend trebuie să fie precauți cu privire la:"],
[["a. Securitatea datelor"],
["b. Calcule adecvate"],
["c. Eficiența utilizării rețelei"],
["d. Toate răspunsurile sunt corecte"],
[3]]],

[["Ce este un model de proiectare în dezvoltarea de software?"],
[["a. Model de tendință în lumea modei"],
["b. Proiectare temă într-un editor de programare"],
["c. Soluție generală reutilizabilă pentru o problemă comună"],
["d. Este un model pentru interfața cu utilizatorul unei aplicații"],
[2]]],

[["Cum aliniați elementele unui container flexibil la centru de-a lungul axei principale?"],
[["a. justify-content: center"],
["b. justify-content: space-around"],
["c. justify-content: flex-end"],
["d. align-items: flex-start"],
[0]]],

[["Pentru ce pot fi folosite expresiile regulate (RegEx)?"],
[["a. Căutarea informațiilor în bucăți mari de text"],
["b. Înlocuirea unor date cu alte date"],
["c. Validarea datelor transmise de utilizatori"],
["d. Toate răspunsurile sunt corecte"],
[3]]],

[["Ce element HTML vă permite să desenați grafică în JS?"],
[["a. < audio>"],
["b. < canvas>"],
["c. < figure>"],
["d. < graphic>"],
[1]]],

[["Ce este un CMS?"],
[["a. Una dintre paradigmele de programare în JavaScript"],
["b. Un software care ajută utilizatorii să creeze, să gestioneze și să modifice conținutul de pe un site web fără a fi nevoie de cunoștințe tehnice specializate"],
["c. Program special pentru crearea desenelor grafice avansate"],
["d. Structura datelor foarte asemănătoare cu un copac sau o coadă"],
[1]]],

[["Ce mod ar trebui să setați în Webpack atunci când dezvoltati aplicația?"],
[["a. production"],
["b. nici unul"],
["c. development"],
["d. advanced"],
[2]]],

[["Care sunt componentele modelului MVC?"],
[["a. Model-View-Controller"],
["b. Marvel-Vision-Captain"],
["c. Mixin-Value-Control"],
["d. Model-View-ViewModel"],
[0]]],

[["Ce sunt “lifecycle hooks” în Angular?"],
[["a. Acestea sunt ciclurile de viață ale oricărei aplicații web care corespund tendințelor de pe Internet"],
["b. Sunt obiecte unice care se execută o singură dată pe durata de viață a aplicației"],
["c. Sunt procesul de injectare a obiectelor dependente într-o clasă dintr-o clasă externă"],
["d. Acestea sunt ciclurile prin care trece fiecare componentă. Ele diferă în ceea ce privește timpul și motivul executării"],
[3]]],

[["De ce este atât de importantă testarea software-ului?"],
[["a. Deoarece cu testarea, mai mulți oameni au locuri de muncă"],
["b. Ajută la câștigarea încrederii clienților și afectează calitatea produsului"],
["c. Nu este deloc important"],
["d. Îmbunătățiți starea de spirit a echipei"],
[1]]],

[["Ce notație veți folosi pentru a pune un comentariu în JavaScript?"],
[["a. # comment"],
["b. < !-- comment -->"],
["c. // comment or /\* comment \*/"],
["d. % comment"],
[2]]],

[["Cum se scrie un obiect în JavScript?"],
[["a. var obj = [...];"],
["b. let obj = {...};"],
["c. const obj = ‘Object’;"],
["d. var obj = /.../;"],
[1]]],

[["Care dintre următoarele sunt modele de proiectare?"],
[["a. Bootstrap, Bulma, Tailwind CSS"],
["b. Singleton, Decorator, MVC"],
["c. Vue, React, Angular"],
["d. Figma, Illustrator, Photoshop"],
[1]]],

[["Ce arată panoul „Surse” din Instrumentele pentru dezvoltatori din browser?"],
[["a. Elemente legate de rețea"],
["b. Toate fișierele utilizate de aplicația noastră"],
["c. Consolă"],
["d. Elemente legate de siguranță"],
[1]]],

[["Cum poate un copil să trimită informații unui părinte în Angular?"],
[["a. Via @Input()"],
["b. Via @Output()"],
["c. Via @Component()"],
["d. Via @NgModule"],
[1]]],

[["Ce nu este HTML?"],
[["a. Un limbaj al etichetelor"],
["b. Un limbaj de programare"],
["c. Un limbaj de marcare hipertext"],
["d. Un limbaj pentru crearea paginilor web"],
[1]]],

[["Ce este un \"parent selector\" în Sass?"],
[["a. Acesta este un selector special folosit pentru a stiliza numai părinții unui element HTML"],
["b. Este o funcție specială pentru care creem un părinte pentru selector"],
["c. Este un selector special care este folosit în selectoarele imbricate pentru a se referi la selectorul exterior"],
["d. Nu există așa ceva"],
[2]]],

[["Care dintre următoarele sunt CSS frameworks?"],
[["a. Angular, Vue, React,"],
["b. Bootstrap, Fundation, Bulma"],
["c. Laravel, Symfony, CodeIgniter"],
["d. Spring, Struts, Hibernate"],
[1]]],

[["Care instrument este cel mai bun atunci când vine vorba de predarea proiectelor către implementare?"],
[["a. Invision"],
["b. Zeplin"],
["c. Avocode"],
["d. Nu există un răspuns corect. Fiecare echipă și proiect are nevoi diferite"],
[3]]],

[["Ce este un callback?"],
[["a. Callback este atunci când trecem o funcție ca argument unei alte funcții"],
["b. Acesta este un apel returnat pentru un apel pierdut"],
["c. Acesta este feedbackul la codul nostru"],
["d. Este o situație care se poate întâmpla pe șinele de tren"],
[0]]],

[["Cum se apelează un constructor de clasă în JavaScript?"],
[["a. movie('Avatar', 2009, 'James Cameron');"],
["b. new movie('Avatar', 2009, 'James Cameron');"],
["c. call movie('Avatar', 2009, 'James Cameron');"],
["d. create movie('Avatar', 2009, 'James Cameron');"],
[1]]],

[["Cum să combinați mai multe șiruri și să le scrieți în mai multe rânduri?"],
[["a. Folosiți doar semnul plus „+”"],
["b. Utilizați metoda de îmbinare"],
["c. Utilizati \"template literals\" (backtick), e.g. `string text`"],
["d. Nu există o astfel de posibilitate"],
[2]]],

[["Ce este o revizuire a codului (core review)?"],
[["a. Revizuirea publică a codului sursă de către critici cunoscuți"],
["b. O revizuire sistematică a codului sursă"],
["c. Evaluați singur codul sursă"],
["d. Acordați codului sursă o notă de la 1 la 10"],
[1]]],

[["De ce este responsabilă regula @font-face?"],
[["a. Vă permite să atașați fonturi personalizate în CSS-ul vostru"],
["b. Setează stilul fontului"],
["c. Vă permite să adăugați decorațiuni unui font"],
["d. Face ca fontul utilizat să fie receptiv"],
[0]]],

[["Ce face “debugger”-ul în timpul depanării?"],
[["a. Distruge tot codul sursă al aplicației"],
["b. Subliniază lucruri importante"],
["c. Întrerupe execuția codului"],
["d. Stabilește puncte de cotitură"],
[2]]],

[["Pentru ce este răspunzător un Model în pattern-ul MVC?"],
[["a. Descrie ce este afișat și conține data folosită de aplicație"],
["b. Descrie cum modelul este afișat folosind template-uri"],
["c. Descrie cum modelul și view-ul sunt conectate între ele"],
["d. Automatizează comunicarea între model și controller"],
[0]]],

[["Cum poate un părinte să trimită informații unui copil în Angular?"],
[["a. Via @Input()"],
["b. Via @Output()"],
["c. Via @Component()"],
["d. Via @NgModule"],
[0]]],

[["Ce sunt flowcharts (block diagrams)?"],
[["a. O reprezentare schematică a unui algoritm"],
["b. Vă permite să determinați numărul exact de locuitori aflați într-un apartament"],
["c. Acestea sunt pur și simplu grafice, cum ar fi diagramele circulare"],
["d. Diagrama care arată ordinea clicurilor în aplicație"],
[0]]],

[["Care este semnul pentru \"at-rule\" in Sass?"],
[["a. &"],
["b. %"],
["c. @"],
["d. $"],
[2]]],

[["Ce este responsive web design?"],
[["a. Este o abordare care permite site-urilor web să se afișeze corespunzător pe toate dispozitivele prin adaptarea automată la ecran"],
["b. Un site web care interacționează ca urmare a acțiunilor efectuate de utilizator"],
["c. Reacția politicienilor la apelurile publice"],
["d. Este genul de design web care implică asumarea responsabilității pentru conținutul pe care îl creați"],
[0]]],

[["De ce este necesara optimizarea imaginilor înainte de a le plasa într-o aplicație web?"],
[["a. Imaginile optimizate câștigă calitate și arată mai bine"],
["b. Alte imagini decât cele optimizate nu pot fi adăugate"],
["c. Astfel de imagini au cel mai bun UX"],
["d. Îmbunătățiți performanța aplicației, accelerați încărcarea aplicației"],
[3]]],

[["Care este domeniul de aplicare (scope) al variabilelor în JavaScript?"],
[["a. Regiunea bazei de cod peste care este valid un identificator"],
["b. Oportunitatea de a face ceva"],
["c. Responsabilitățile programatorului"],
["d. Intervalul de tip în care operează variabila"],
[0]]],

[["Cum se apelează metoda „info” din obiectul ‘’movie”?"],
[["a. movie->info();"],
["b. movie.info();"],
["c. info.movie();"],
["d. movie[methods]info();"],
[1]]],

[["Care dintre următoarele sunt concepte de design (design patterns) utile?"],
[["a. KISS"],
["b. DRY"],
["c. SOLID"],
["d. Toate răspunsurile sunt corecte"],
[3]]],

[["Cum să rotunjesc laturile unui element în CSS?"],
[["a. Utilizați proprietatea \"round\""],
["b. Utilizați proprietatea \"corner-round\""],
["c. Utilizați proprietatea \"flex\""],
["d. Utilizați proprietatea \"border-radius\""],
[3]]],

[["Ce este debugging?"],
[["a. Acesta este procesul prin care clientul interogează serverul"],
["b. Găsirea erorilor și încercarea de a le remedia"],
["c. Găsirea insectelor și pregătirea cinei din ele"],
["d. Funcție JavaScript specială pentru crearea codului asincron"],
[1]]],

[["Cum gestionați eventul de “click” pe un element?"],
[["a. x.whenClick = function() {...}"],
["b. x.onclick = function() {...}"],
["c. x.clicked(() => {...})"],
["d. x.on(‘click’, function() {...}"],
[1]]],

[["Unde folosim CMS?"],
[["a. Websites,"],
["b. E-Commerce,"],
["c. Web and Mobile Applications,"],
["d. Toate răspunsurile sunt corecte"],
[3]]],

[["De ce este responsabil “View” în modelul MVC?"],
[["a. Descrie ceea ce este afișat, conține datele aplicației"],
["b. Descrie modul în care sunt afișate datele modelului folosind view-uri"],
["c. Descrie modul în care partea de model și partea de vizualizare se conectează între ele"],
["d. Automatizează comunicarea între model și controller"],
[1]]],

[["Ce sunt lifecycle hooks în Angular?"],
[["a. Acestea sunt ciclurile de viață ale oricărei aplicații web care se mapează la tendințele de pe Internet"],
["b. Sunt obiecte unice care sunt rulate o singură dată pe durata de viață a aplicației"],
["c. Sunt procesul de injectare a obiectelor dependente într-o clasă dintr-o clasă externă"],
["d. Acestea sunt ciclurile prin care trece fiecare componentă. Ele diferă în timp și motiv pentru execuție"],
[3]]],

[["Ce face \"@import\"at-rule in Sass?"],
[["a. Încarcă mixuri, funcții și variabile din alte fișiere SASS"],
["b. Acesta definește o bucată reutilizabilă de cod SASS"],
["c. Importă conținutul fișierului CSS extern în fișierul curent"],
["d. Vă permite să definiți o funcție"],
[2]]],

[["Ce este un Grid System?"],
[["a. O tehnologie pentru a vă îngrădi casa în siguranță"],
["b. Acesta este numele sistemului de operare pentru computere"],
["c. O structură care cuprinde o serie de linii orizontale și verticale, utilizate pentru aranjarea conținutului"],
["d. Nume comun pentru tabelele în HTML"],
[2]]],

[["Care sunt bunele practici în munca de proiectare?"],
[["a. Discutați deciziile de proiectare"],
["b. Reîncadrați cerințele"],
["c. Acordați atenție detaliilor"],
["d. Toate răspunsurile sunt corecte"],
[3]]],

[["Ce este recursiunea?"],
[["a. Recursiunea este atunci când un program sau o funcție se autoapelează"],
["b. Este atunci când credem că am făcut deja ceva"],
["c. Referire la resursele programului"],
["d. Este cel mai comun format de trimitere a datelor"],
[0]]],

[["Ce permite proprietatea Prototype din JavaScript?"],
[["a. Vă permite să utilizați mostenirea (inheritance)"],
["b. Permite crearea de prototipuri a aplicației"],
["c. Nu există așa ceva în JS"],
["d. Activează modul adevărat dezvoltator"],
[0]]],

[["Ce este arhitectura client-server?"],
[["a. Arhitectură specială pentru industria comerțului electronic"],
["b. Arhitectură în care clientul oferă servicii serverelor"],
["c. Arhitectură exclusiv pentru clienții magazinului nostru"],
["d. O arhitectură în care serverul oferă servicii clienților care fac cereri de servicii către server"],
[3]]],

[["Cum se adaugă o umbra (shadow) unui text în CSS?"],
[["a. Se utilizează proprietatea\"text-shadow\""],
["b. Se utilizează proprietatea \"box-shadow\""],
["c. Se utilizează proprietatea \"font-shadow\""],
["d. Se utilizează proprietatea \"shadow\""],
[0]]],

[["Care dintre CMS-urile enumerate este cel mai popular din lume?"],
[["a. Joomla"],
["b. Drupal"],
["c. Squarespace"],
["d. WordPress"],
[3]]],

[["Pe care dintre următoarele instrumente le veți folosi ca bundler de module?"],
[["a. Webpack"],
["b. Sass"],
["c. WordPress"],
["d. FileZilla"],
[0]]],

[["Ce este HTML?"],
[["a. Un limbaj de programare"],
["b. Un plug-in de browser"],
["c. Un limbaj al etichetelor"],
["d. Un software pentru crearea de pagini web"],
[2]]],

[["Ce este un algoritm?"],
[["a. O modalitate definită de a rezolva o problemă într-un număr finit de pași"],
["b. Ritmul în care dansează algele marine"],
["c. O ecuație integrală cu expirare definită"],
["d. O încercare de a rezolva o problemă fără presupuneri"],
[0]]], 

[["Care dintre următoarele sunt preprocesoare CSS?"],
[["a. Sass"],
["b. Less"],
["c. Stylus"],
["d. Toate răspunsurile sunt corecte"],
[3]]],

[["Cum poți scrie o funcție anonimă în JS?"],
[["a. function(a) { return a \* 5; }"],
["b. function foo(a) { return a \* 5; }"],
["c. function< anonymous>(a) { return a \* 5; }"],
["d. function SuperSecretName(a) { return a \* 5; }"],
[0]]],

[["Care dintre următoarele sunt design patterns?"],
[["a. Bootstrap, Bulma, Tailwind CSS"],
["b. Singleton, Decorator, MVC"],
["c. Vue, React, Angular"],
["d. Figma, Illustrator, Photoshop"],
[1]]],

[["Cum se adaugă o umbră (shadow) textului în CSS?"],
[['a. Folosind proprietatea "text-shadow"'],
['b. Folosind proprietatea "box-shadow"'],
['c. Folosind proprietatea "font-shadow"'],
['d. Folosind proprietatea "shadow"'],
[0]]],

[['Ce face funcția "console.log()"?'],
[["a. Afișează text în consolă"],
["b. Controlează comportamentul consolei"],
["c. Afișează istoricul jurnalului consolei"],
["d. Conectați utilizatorul la consolă"],
[0]]],

[["De ce este responsabil un “View” în modelul MVC?"],
[["a. Descrie ceea ce este afișat, conține datele aplicației"],
["b. Descrie modul în care sunt afișate datele modelului folosind view-uri"],
["c. Descrie modul în care partea de model și partea de vizualizare se conectează între ele"],
["d. Automatizează comunicarea între model și controler"],
[1]]],

[["În ce limbă este scris framework-ul Angular?"],
[["a. CoffeScript"],
["b. JavaScript"],
["c. TypeScript"],
["d. SuperScript"],
[2]]],

];